language: python
python:
- 3.6.3
addons:
  chrome: stable
before_install:
- sudo apt-get install chromium-chromedriver
- sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
- pip install -r requirements.txt
- pip install -r dev-requirements.txt
sudo: required
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
   - secure: S14yl/tkgjNW9KOLHNyUI/vjjqHgSI/zQmWODjEb9tqfPiteY0Jm70IKR/5BN/YBFFVM/j6b9T9QFV/iCNdLxTyh35xWEoYwo9rzaS05Rn/k06iDFRqG/u16A/1O+jPxXKl/SK7QYe9etPmv2vGByRk8j+KKtnF0aJCm0KyNxmcHRGE5vkd8Suxvu+dlGiod3yFrcyQAtYkUvj+JE5IuHrj1PrM+7JvHlI649vXnsBnSsQ3zKfyYujWdTWKrqLn/1F5mEYc5Grfq9XX+LC3F6BE8GEzBYjBzstC5HONir2Y8meSGm67M9sY1Jh2mncHW/UgSjLa/x8i7WZT6raCal4GbfcFTJD/i96IsrR49qmd87pdh3QGuCIjRNHjLDhU8DOQCTG2Lfx4WpmzzMPu1e8jTdch6lKCgsgtGdbXsjU5qkj0hm9uBi9KdM7S7QCIWNhERaKXIpdTPSj6ccGTz5HEWwScvU2kx0Gydp2s47UgDnBvXFgHoSsQd5mQmPRKtn3ilFN9Y/MxogwijHGLRNquWRed2wQ6G2zNwG6Aqqk6nfWYqqkyrmJP9g0zQQJDE0FggwBOK+jve5FPrRZ8wvQBl9em4d+flkT+lxYo2JHOpIq9QX9xxi6NiSOIHZMBFhrjZKM/IXLq0Q+OjrFVZ+7Popdcl3v4DO7SLmFdmuT0=
  app: superlists
  on:
    repo: SunFrogThe/superlists
  run:
  - python manage.py makemigrations
  - python manage.py migrate
