language: python
python:
- 3.6.3
addons:
  chrome: stable
before_install:
- sudo apt-get install chromium-chromedriver
- sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
install:
- pip install -r requirements.txt
- pip install -r dev-requirements.txt
sudo: required
script:
- python manage.py test
deploy:
  provider: heroku
  app: django-tdd-superlists
  api_key:
    secure: pWuiQ8/wCLGSjuC5iCJNKlVPXz0sRB9boMJ4mIuZLwXHxVm6NVAuviS7Aw4w6GSSwJSMagGcAoq0GGr7i9J9/SoAQ1xbYdruU1YX+LaupMz2dtlyvL48hMbBIaK2loHGVMT89kF07578ebvX0psbb4X3wN1o0vIy3oIMEFjhOA//i8A/VgqdWXW41NxepfaEoSvyhBSy3PChXl79PKMImwfxPXRMRkahqyZywQXIRp+iMIpbhB7OjpANe+u1USF2h74AnshhS5AbdmCLRwoKcP/xXx0A36jaOy1HWohDoSZXFxxQBM6ry0BvaHOs34Rv8SCgp/jtBIitHqrPB5EChJMXcVkt/LcQAXbYqjtO18KAu90jE5m1hc+qU7DQuESZKhV1YRTg3NAYkQinUjENFSNax2V7ZcD5+brzT4/3X5+i77TOJJ4RlFjm8hVIfX0z8B/Q/BsEC1tc6mqAqR0jn96PYi9iXSOuHt0KEFYO47DaSv2FmJNcWLKFGoxDfpUJmbDZYwIJPnBLOlrIqKJBnG6DvOJLBxRjy6OsXBiBrWGmcM9w77sNm2+rKWXn+Tc40wOExg7zohxdmh5SAREe28SlLwRKCtFOiNHA7wCg4Q/kVmA384rHWLnZdtkdB/j5l6WVXv9nTgI3bcx4IafCRJ6r66ToP+qkLYh5XCbNEdY=
  run:
  - python manage.py makemigrations
  - python manage.py migrate
